stages:
  - deploy

deploy dev:
  stage: deploy
  script:
    - ENVIRONMENT="dev"
    - APPLICATION="rentit-ui"
    - REMOTE_FOLDER="/var/www/html/$ENVIRONMENT/$APPLICATION"
    - REMOTE_SERVICE_OWNER="gitlab-runner"
    - echo $GITLAB_RUNNER_PASSWORD | chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
    - echo $GITLAB_RUNNER_PASSWORD | rm -rf ./package-lock.json
    - echo $GITLAB_RUNNER_PASSWORD | rm -rf ./node_modules
    - echo $GITLAB_RUNNER_PASSWORD | rm -rf ./dist
    - echo $GITLAB_RUNNER_PASSWORD | npm install
    - echo $GITLAB_RUNNER_PASSWORD | ng build --base-href / --configuration=$ENVIRONMENT
    - echo $GITLAB_RUNNER_PASSWORD | mkdir -p $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | cp -rf ./dist/* $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
  environment: development
  when: manual

deploy test:
  stage: deploy
  script:
    - ENVIRONMENT="test"
    - APPLICATION="rentit-ui"
    - REMOTE_FOLDER="/var/www/html/$ENVIRONMENT/$APPLICATION"
    - REMOTE_SERVICE_OWNER="gitlab-runnerv"
    - echo $GITLAB_RUNNER_PASSWORD | chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
    - echo $GITLAB_RUNNER_PASSWORD | rm -rf ./package-lock.json
    - echo $GITLAB_RUNNER_PASSWORD | rm -rf ./node_modules
    - echo $GITLAB_RUNNER_PASSWORD | rm -rf ./dist
    - echo $GITLAB_RUNNER_PASSWORD | npm install
    - echo $GITLAB_RUNNER_PASSWORD | ng build --base-href / --configuration=$ENVIRONMENT
    - echo $GITLAB_RUNNER_PASSWORD | mkdir -p $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | cp -rf ./dist/* $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
  environment: development
  when: manual

deploy prod:
  stage: deploy
  script:
    - ENVIRONMENT="prod"
    - APPLICATION="rentit-ui"
    - REMOTE_FOLDER="/var/www/html/$ENVIRONMENT/$APPLICATION"
    - REMOTE_SERVICE_OWNER="gitlab-runner"
    - echo $GITLAB_RUNNER_PASSWORD | chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
    - echo $GITLAB_RUNNER_PASSWORD | rm -rf ./package-lock.json
    - echo $GITLAB_RUNNER_PASSWORD | rm -rf ./node_modules
    - echo $GITLAB_RUNNER_PASSWORD | rm -rf ./dist
    - echo $GITLAB_RUNNER_PASSWORD | npm install
    - echo $GITLAB_RUNNER_PASSWORD | ng build --base-href / --configuration=$ENVIRONMENT
    - echo $GITLAB_RUNNER_PASSWORD | mkdir -p $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | cp -rf ./dist/* $REMOTE_FOLDER
    - echo $GITLAB_RUNNER_PASSWORD | chown -R $REMOTE_SERVICE_OWNER:$REMOTE_SERVICE_OWNER .
  environment: development
  when: manual
